### PR TITLE
added package.json

### PR DESCRIPTION
**Pull request by izifortune**
Added package.json for the repository

### CODE REVIEW

**Comment by AnalogJ** [comment]
Hmm this is a good idea. I'll upload it to NPM this afternoon.

**Comment by AnalogJ** [comment]
Hey @izifortune you're pull request is going to be the guinea pig for a library I just wrote to handle PR's. I may have to close/open the PR a few times, sorry.

**Comment by AnalogJ** [comment]
The npm package is registered at v1.0.8 - https://www.npmjs.com/package/matchmedia-ng

Thanks again for the PR

**Comment by izifortune** [comment]
Thank you,

I'm try to switch to npm only dependencies and having this it's great.

**Pull request merged**
